language: php

php:
  - 7.1

branches:
  only:
    - master
    - develop

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - export PHP_MAJOR_VERSION=$(php -r "echo PHP_MAJOR_VERSION;")

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=.phpcs.xml
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

after_script:
  - vendor/bin/coveralls

notifications:
  irc: "chat.freenode.net#thedevnetwork"
  email: vpassapera@gmail.com

notifications:
  on_success: never
  on_failure: always
